CREATE TABLE boxscores(
  id INT AUTO_INCREMENT NOT NULL,
  game_id INT,
  gameDate VARCHAR(255),
  awayTeam VARCHAR(255),
  homeTeam VARCHAR(255),
  lastMeetingWinner VARCHAR(255),
  q1AwayPts INT,
  q2AwayPts INT,
  q3AwayPts INT,
  q4AwayPts INT,
  q1HomePts INT, 
  q2HomePts INT,
  q3HomePts INT,
  q4HomePts INT,
  referee1 VARCHAR(255),
  referee2 VARCHAR(255),
  referee3 VARCHAR(255),
  timesTied INT,
  leadChanges INT,
  winner VARCHAR(255),
  createdAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  updatedAt DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(id),
  INDEX(game_id),
  FOREIGN KEY(game_id) REFERENCES games(game_id)
);